apiVersion: v1
kind: Pod
metadata:
  name: simple-website
spec:
  containers:
    - name: simple
      image: simple_statis_website:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: "300Mi"